CREATE DATABASE IF NOT EXISTS BBDD_PAISES;

USE BBDD_PAISES;

CREATE TABLE MONEDAS(

    ID_MONEDA INT UNSIGNED AUTO_INCREMENT NOT NULL,
    NOMBRE TEXT NOT NULL,

    PRIMARY KEY (ID_MONEDA)

) ENGINE MYISAM;

CREATE TABLE IF NOT EXISTS MONEDAS_PAISES(

     ID_MONEDA INT UNSIGNED NOT NULL,
     ID_PAIS INT UNSIGNED NOT NULL,

     FOREIGN KEY FK_MONEDA(ID_MONEDA) REFERENCES MONEDAS(ID_MONEDA)
         ON DELETE RESTRICT
         ON UPDATE CASCADE,

     FOREIGN KEY FK_PAIS(ID_PAIS) REFERENCES PAISES(ID_PAIS)
         ON DELETE CASCADE
         ON UPDATE CASCADE,

     PRIMARY KEY (ID_PAIS, ID_MONEDA)

) ENGINE INNODB;

CREATE TABLE IF NOT EXISTS PAISES(

     ID_PAIS INT UNSIGNED AUTO_INCREMENT NOT NULL,
     NOMBRE TEXT NOT NULL,
     NUM_HABITANTES INT UNSIGNED NOT NULL,
     CAPITAL TEXT NOT NULL,

     PRIMARY KEY (ID_PAIS),
     UNIQUE INDEX AK_NOMBRE(NOMBRE)

)ENGINE MYISAM;